import { config } from 'dotenv'
import { drizzle } from 'drizzle-orm/postgres-js'
import postgres from 'postgres'
import { schemes } from './schema'

config({ path: '.env.local' })

if (!process.env.DATABASE_URL) {
  throw new Error('DATABASE_URL is not set')
}

const connectionString = process.env.DATABASE_URL
const client = postgres(connectionString)
const db = drizzle(client)

const SEED_SCHEMES = [
  {
    slug: 'kisan-samman-nidhi',
    title: 'Kisan Samman Nidhi',
    description: 'Income support to all landholding farmers families in the country.',
    category: 'Agriculture',
    targetGroup: 'Farmers',
    benefits: 'Rs. 6000 per year in three equal installments.',
    eligibility: 'All landholding farmers families, having cultivable land in their names.',
    applicationProcess: 'Apply online on pmkisan.gov.in or via CSC.',
    requiredDocuments: ['Aadhaar Card', 'Bank Account Details', 'Land Holding Documents'],
    officialUrl: 'https://pmkisan.gov.in',
    ministry: 'Ministry of Agriculture and Farmers Welfare',
    schemeType: 'Central Sector Scheme',
    occupationTags: ['farmer', 'agriculture'],
    stateTags: [],
    genderTags: [],
    educationTags: [],
    ageMin: 18,
    ageMax: null,
    incomeMin: null,
    incomeMax: null,
    isActive: true,
  },
  {
    slug: 'national-scholarship-scheme',
    title: 'National Means cum Merit Scholarship',
    description: 'Scholarships for meritorious students of economically weaker sections.',
    category: 'Education',
    targetGroup: 'Students',
    benefits: 'Rs. 12000 per annum (Rs. 1000 per month).',
    eligibility: 'Students studying in Class IX. Parental income should not exceed Rs. 3,50,000 per annum.',
    applicationProcess: 'Apply through National Scholarship Portal.',
    requiredDocuments: ['Income Certificate', 'Aadhaar Card', 'School ID', 'Bank Account Details'],
    officialUrl: 'https://scholarships.gov.in',
    ministry: 'Ministry of Education',
    schemeType: 'Centrally Sponsored Scheme',
    occupationTags: ['student'],
    stateTags: [],
    genderTags: [],
    educationTags: [],
    ageMin: 13,
    ageMax: 16,
    incomeMin: null,
    incomeMax: '350000',
    isActive: true,
  },
  {
    slug: 'doctor-rural-incentive-mp',
    title: 'Doctor Rural Incentive Scheme (MP)',
    description: 'Incentive for medical professionals to serve in rural areas of Madhya Pradesh.',
    category: 'Healthcare',
    targetGroup: 'Medical Professionals',
    benefits: 'Additional 20% to 30% of basic salary as incentive.',
    eligibility: 'Must be a registered medical practitioner working in designated rural or tribal health centers in MP.',
    applicationProcess: 'Submit joining report at the respective CMHO office.',
    requiredDocuments: ['Medical Registration Certificate', 'Posting Order', 'Bank Account Details'],
    officialUrl: 'https://health.mp.gov.in',
    ministry: 'Department of Public Health and Family Welfare (MP)',
    schemeType: 'State Scheme',
    occupationTags: ['doctor', 'medical', 'nurse', 'healthcare'],
    stateTags: ['madhya_pradesh'],
    genderTags: [],
    educationTags: ['bachelor', 'master'],
    ageMin: 22,
    ageMax: 60,
    incomeMin: null,
    incomeMax: null,
    isActive: true,
  },
  {
    slug: 'mukhyamantri-kanya-vivah-yojana',
    title: 'Mukhyamantri Kanya Vivah Yojana',
    description: 'Financial assistance for the marriage of girls from poor families.',
    category: 'Social Welfare',
    targetGroup: 'Women from poor families',
    benefits: 'Financial assistance of Rs. 51,000 for marriage.',
    eligibility: 'The girl must be 18 years or above. The family must be domiciled in Madhya Pradesh and living below the poverty line.',
    applicationProcess: 'Apply at Gram Panchayat / Janpad Panchayat or Urban Local Body.',
    requiredDocuments: ['Age Proof', 'BPL Card', 'Domicile Certificate', 'Bank Account Details'],
    officialUrl: 'http://samagra.gov.in',
    ministry: 'Department of Social Justice and Disabled Person Welfare',
    schemeType: 'State Scheme',
    occupationTags: [],
    stateTags: ['madhya_pradesh'],
    genderTags: ['female'],
    educationTags: [],
    ageMin: 18,
    ageMax: null,
    incomeMin: null,
    incomeMax: '100000',
    isActive: true,
  },
  {
    slug: 'pm-mudra-yojana',
    title: 'Pradhan Mantri Mudra Yojana (PMMY)',
    description: 'Provides loans up to 10 lakh to the non-corporate, non-farm small/micro enterprises.',
    category: 'Business & Entrepreneurship',
    targetGroup: 'Small business owners, Entrepreneurs',
    benefits: 'Collateral free loans classified into Shishu (upto 50,000), Kishore (50,000 to 5 Lakh) and Tarun (5 Lakh to 10 Lakh).',
    eligibility: 'Any Indian Citizen who has a business plan for a non-farm sector income generating activity.',
    applicationProcess: 'Apply at any bank, NBFC, MFI or online at Udyamimitra portal.',
    requiredDocuments: ['Identity Proof', 'Address Proof', 'Business Proof', 'Project Report'],
    officialUrl: 'https://www.mudra.org.in',
    ministry: 'Ministry of Finance',
    schemeType: 'Central Sector Scheme',
    occupationTags: ['business', 'entrepreneur', 'self_employed'],
    stateTags: [],
    genderTags: [],
    educationTags: [],
    ageMin: 18,
    ageMax: 65,
    incomeMin: null,
    incomeMax: null,
    isActive: true,
  },
  {
    slug: 'ladli-laxmi-yojana',
    title: 'Ladli Laxmi Yojana',
    description: 'Welfare scheme by the Government of Madhya Pradesh to improve the educational, health, and economic status of girl children.',
    category: 'Education & Welfare',
    targetGroup: 'Girl children and their families',
    benefits: 'Total of ₹1.18 lakh financial assistance at various stages of the girl\'s life to support her education and discourage child marriage.',
    eligibility: 'Girls born on or after Jan 1, 2006. Parents must be residents of MP, non-income tax payers, with max two children.',
    applicationProcess: 'Apply directly through Anganwadi worker or online portal.',
    requiredDocuments: ['Birth Certificate', 'Aadhaar Card', 'Samagra ID', 'Bank Account Details', 'Photo'],
    officialUrl: 'http://ladlilaxmi.mp.gov.in/',
    ministry: 'Women and Child Development Department (MP)',
    schemeType: 'State Scheme',
    occupationTags: [],
    stateTags: ['madhya_pradesh'],
    genderTags: ['female'],
    educationTags: [],
    ageMin: 0,
    ageMax: 21,
    incomeMin: null,
    incomeMax: '250000',
    isActive: true,
  },
  {
    slug: 'ladli-behna-yojana',
    title: 'Mukhyamantri Ladli Behna Yojana',
    description: 'Initiative by Madhya Pradesh Government to empower women economically, improve health, and enhance decision-making.',
    category: 'Social Welfare',
    targetGroup: 'Married women (including widows, divorced)',
    benefits: 'Monthly financial aid of ₹1,250 (₹15,000 annually) transferred via DBT.',
    eligibility: 'Married women aged 21 to 60 years. Permanent residents of MP. Combined family income less than ₹2.5 lakh. Non-income tax payers.',
    applicationProcess: 'Apply online on official portal or at designated Gram Panchayat / Ward offices.',
    requiredDocuments: ['Aadhaar Card', 'Samagra ID', 'Bank Passbook (Aadhaar linked)', 'Residency Proof'],
    officialUrl: 'https://cmladlibahna.mp.gov.in',
    ministry: 'Women and Child Development Department (MP)',
    schemeType: 'State Scheme',
    occupationTags: [],
    stateTags: ['madhya_pradesh'],
    genderTags: ['female'],
    educationTags: [],
    ageMin: 21,
    ageMax: 60,
    incomeMin: null,
    incomeMax: '250000',
    isActive: true,
  },
  {
    slug: 'sukanya-samriddhi-yojana',
    title: 'Sukanya Samriddhi Yojana',
    description: 'A government-backed savings scheme targeted at the parents of girl children, offering high interest rates and tax benefits.',
    category: 'Education & Welfare',
    targetGroup: 'Girl children',
    benefits: 'High interest rate, tax deductions under Section 80C, and financial security for the girl child\'s future education and marriage.',
    eligibility: 'Parents or legal guardians of a girl child. The account must be opened before the girl reaches 10 years of age. Maximum 2 accounts per family.',
    applicationProcess: 'Open an account at any post office or authorized commercial bank branches.',
    requiredDocuments: ['Birth Certificate of Girl Child', 'Identity Proof of Parent', 'Address Proof of Parent'],
    officialUrl: 'https://www.nsiindia.gov.in',
    ministry: 'Ministry of Finance',
    schemeType: 'Central Sector Scheme',
    occupationTags: [],
    stateTags: [],
    genderTags: ['female'],
    educationTags: [],
    ageMin: 0,
    ageMax: 10,
    incomeMin: null,
    incomeMax: null,
    isActive: true,
  },
  {
    slug: 'ayushman-bharat-pm-jay',
    title: 'Ayushman Bharat PM-JAY',
    description: 'The world\'s largest health insurance/ assurance scheme fully financed by the government, providing a cover of Rs. 5 lakhs per family per year for secondary and tertiary care hospitalization.',
    category: 'Healthcare',
    targetGroup: 'Poor and vulnerable families (BPL)',
    benefits: 'Health cover of Rs. 5 lakhs per family per year for secondary and tertiary care hospitalization across public and private empaneled hospitals in India.',
    eligibility: 'Based on the deprivation and occupational criteria of the Socio-Economic Caste Census (SECC) 2011.',
    applicationProcess: 'Verify eligibility at PMJAY portal or hospital, generate Golden Card using Aadhaar and Ration Card.',
    requiredDocuments: ['Aadhaar Card', 'Ration Card', 'Mobile Number'],
    officialUrl: 'https://pmjay.gov.in',
    ministry: 'Ministry of Health and Family Welfare',
    schemeType: 'Centrally Sponsored Scheme',
    occupationTags: [],
    stateTags: [],
    genderTags: [],
    educationTags: [],
    ageMin: null,
    ageMax: null,
    incomeMin: null,
    incomeMax: '100000',
    isActive: true,
  },
  {
    slug: 'post-matric-scholarship-sc-st',
    title: 'Post Matric Scholarship for SC/ST',
    description: 'Financial assistance to Scheduled Caste/Scheduled Tribe students studying at post matriculation or post-secondary stage to enable them to complete their education.',
    category: 'Education',
    targetGroup: 'SC/ST Students',
    benefits: 'Covers maintenance allowance, reimbursement of compulsory non-refundable fees, study tour charges, and thesis typing/printing charges.',
    eligibility: 'Students belonging to SC/ST categories studying in recognized post-matriculation courses. Parental income should not exceed Rs. 2.5 lakhs per annum.',
    applicationProcess: 'Apply online via the National Scholarship Portal (NSP) or respective state portals.',
    requiredDocuments: ['Caste Certificate', 'Income Certificate', 'Aadhaar Card', 'Bank Account Details', 'Fee Receipt', 'Previous Year Marksheet'],
    officialUrl: 'https://scholarships.gov.in',
    ministry: 'Ministry of Social Justice and Empowerment / Tribal Affairs',
    schemeType: 'Centrally Sponsored Scheme',
    occupationTags: ['student'],
    stateTags: [],
    genderTags: [],
    educationTags: [],
    ageMin: 15,
    ageMax: null,
    incomeMin: null,
    incomeMax: '250000',
    isActive: true,
  },
  {
    slug: 'mukhya-mantri-yuva-swarozgar-yojana-up',
    title: 'Mukhya Mantri Yuva Swarozgar Yojana (UP)',
    description: 'Provides financial assistance to the educated unemployed youth of Uttar Pradesh to start their own enterprise/industry.',
    category: 'Business & Entrepreneurship',
    targetGroup: 'Unemployed Youth in UP',
    benefits: 'Margin money subsidy up to 25% of the project cost. Max loan for industry is Rs. 25 Lakhs, and for service sector is Rs. 10 Lakhs.',
    eligibility: 'Age between 18 to 40 years. Minimum education: High School pass. Must be a resident of Uttar Pradesh and not a defaulter in any bank.',
    applicationProcess: 'Apply online through the Diwan-e-Swarozgar portal.',
    requiredDocuments: ['Aadhaar Card', 'Age Proof', 'Educational Certificate', 'Domicile Certificate (UP)', 'Project Report'],
    officialUrl: 'https://diupmsme.upsdc.gov.in',
    ministry: 'Department of MSME and Export Promotion (UP)',
    schemeType: 'State Scheme',
    occupationTags: ['student', 'unemployed', 'business', 'entrepreneur'],
    stateTags: ['uttar_pradesh'],
    genderTags: [],
    educationTags: ['high_school', 'bachelor', 'master'],
    ageMin: 18,
    ageMax: 40,
    incomeMin: null,
    incomeMax: null,
    isActive: true,
  },
  {
    slug: 'ignoaps-old-age-pension',
    title: 'Indira Gandhi National Old Age Pension Scheme',
    description: 'A non-contributory pension scheme that provides monthly financial assistance to elderly citizens living below the poverty line.',
    category: 'Social Welfare',
    targetGroup: 'Senior Citizens',
    benefits: 'Monthly pension. Rs. 200/month for age 60-79 years, and Rs. 500/month for age 80 years and above. (States often contribute matching or higher amounts).',
    eligibility: 'Age must be 60 years or above. Must belong to a Below Poverty Line (BPL) family.',
    applicationProcess: 'Apply through the Gram Panchayat or corresponding urban local body, or via the NSAP online portal.',
    requiredDocuments: ['Age Proof', 'BPL Card', 'Bank Account Details', 'Aadhaar Card'],
    officialUrl: 'https://nsap.nic.in',
    ministry: 'Ministry of Rural Development',
    schemeType: 'Centrally Sponsored Scheme',
    occupationTags: [],
    stateTags: [],
    genderTags: [],
    educationTags: [],
    ageMin: 60,
    ageMax: null,
    incomeMin: null,
    incomeMax: '100000',
    isActive: true,
  }
]

async function seed() {
  console.log('Seeding schemes...')
  try {
    for (const scheme of SEED_SCHEMES) {
      await db.insert(schemes)
        .values(scheme)
        .onConflictDoUpdate({
          target: schemes.slug,
          set: scheme,
        })
      console.log(`Upserted scheme: ${scheme.slug}`)
    }
    console.log('Seeding complete!')
  } catch (error) {
    console.error('Error seeding schemes:', error)
  } finally {
    await client.end()
  }
}

seed()
