export const seedSchemesBatch2 = [
  {
    slug: "pradhan-mantri-jeevan-jyoti-bima-yojana-pmjjby",
    title: "Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)",
    description: "A government-backed term life insurance scheme offering affordable one-year life cover, renewable annually, providing financial protection against death due to any cause.",
    category: "Insurance & Social Security",
    targetGroup: "Savings bank account holders who wish to secure an affordable term life insurance plan.",
    benefits: "Provides a term life insurance coverage of ₹2 Lakh to the nominee in case of death of the subscriber due to any cause.",
    eligibility: "All individual bank or post office savings account holders who give consent to join and enable auto-debit features.",
    applicationProcess: "Enrolment is handled directly by the bank holding the individual's savings account via simple auto-debit consent forms, mobile banking apps, or SMS integration services.",
    requiredDocuments: ["Aadhaar Card", "Bank Passbook", "Nominee Details Form"],
    officialUrl: "https://financialservices.gov.in/pmjjby",
    startDate: "2015-06-01",
    endDate: null,
    ministry: "Ministry of Finance",
    schemeType: "Central Sector",
    occupationTags: ["All", "Salaried", "Self-Employed", "Laborer"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 50,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "pradhan-mantri-suraksha-bima-yojana-pmsby",
    title: "Pradhan Mantri Suraksha Bima Yojana (PMSBY)",
    description: "An ultra-affordable accident insurance scheme offering one-year coverage for accidental death and disability, renewable from year to year.",
    category: "Insurance & Social Security",
    targetGroup: "Savings bank account holders seeking accidental death and total/partial disability insurance.",
    benefits: "Provides ₹2 Lakh for accidental death or total irrecoverable loss of both eyes/hands/feet, and ₹1 Lakh for permanent partial disability.",
    eligibility: "All individual bank or post office savings account holders who provide an auto-debit mandate for the nominal ₹20 yearly premium.",
    applicationProcess: "Can be easily joined through net banking portals, official mobile apps, or by filling out a basic application form at local bank branches.",
    requiredDocuments: ["Aadhaar Card", "Bank Account Details", "Nominee Declaration Profile"],
    officialUrl: "https://financialservices.gov.in",
    startDate: "2015-06-01",
    endDate: null,
    ministry: "Ministry of Finance",
    schemeType: "Central Sector",
    occupationTags: ["All", "Laborer", "Driver", "Technician"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 70,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "pradhan-mantri-kaushal-vikas-yojana-pmkvy",
    title: "Pradhan Mantri Kaushal Vikas Yojana (PMKVY 4.0)",
    description: "The flagship outcome-based skill training scheme aimed at enabling Indian youth to take up industry-relevant skill training that helps them secure a better livelihood.",
    category: "Skill Development & Employment",
    targetGroup: "Unemployed youth, school dropouts, and informal sector workers seeking formal certification.",
    benefits: "Provides 100% free industry-aligned technical training, government-recognized NSDC certification, mandatory On-the-Job Training (OJT), direct connection to job portals, and a travel/stipend incentive.",
    eligibility: "Any Indian national who is currently unemployed, out of school/college, or working informally without formal credentials.",
    applicationProcess: "Registration must be filled online on the Skill India Digital Hub (SIDH) platform where candidates search for certified local training complexes.",
    requiredDocuments: ["Aadhaar Card", "Educational Certificates or School Leaving Certificate", "Bank Passbook"],
    officialUrl: "https://www.skillindiadigital.gov.in",
    startDate: "2015-07-15",
    endDate: "2026-12-31",
    ministry: "Ministry of Skill Development and Entrepreneurship",
    schemeType: "Central Sector",
    occupationTags: ["Unemployed", "Student", "Laborer", "Technician"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["Under 10th", "10th Pass", "12th Pass", "Graduate"],
    ageMin: 15,
    ageMax: 45,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "pradhan-mantri-fasal-bima-yojana-pmfby",
    title: "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
    description: "A comprehensive crop insurance program offering financial security against crop failures arising from non-preventable natural risks like droughts, floods, pests, and localized calamities.",
    category: "Agriculture",
    targetGroup: "All farmers growing notified food, oilseeds, and commercial/horticultural crops within notified geographic areas.",
    benefits: "Financial payouts for crop yield damage. Premium is highly subsidized: capped at 2% for Kharif crops, 1.5% for Rabi crops, and 5% for commercial/horticultural crops.",
    eligibility: "Both loanee (default via crop loans) and non-loanee farmers holding land holding credentials for designated notified regional crops.",
    applicationProcess: "Farmers can apply directly through the National Crop Insurance Portal (NCIP), localized banking branches, or authorized insurance agents.",
    requiredDocuments: ["Aadhaar Card", "Land Possession Certificate / Land Records", "Sowing Certificate issued by local official", "Cancelled Cheque / Bank Passbook"],
    officialUrl: "https://pmfby.gov.in",
    startDate: "2016-02-18",
    endDate: null,
    ministry: "Ministry of Agriculture and Farmers Welfare",
    schemeType: "Centrally Sponsored",
    occupationTags: ["Farmer"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 100,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "national-apprenticeship-promotion-scheme-naps",
    title: "National Apprenticeship Promotion Scheme (NAPS)",
    description: "An employment generation scheme designed to catalyze active apprenticeship setups by sharing the cost of structural training stipends with prospective corporate employers.",
    category: "Skill Development & Employment",
    targetGroup: "Technical graduates, ITI pass outs, diploma holders, and fresh apprentices seeking workplace skill exposure.",
    benefits: "Direct sharing of 25% of the prescribed monthly stipend (up to a ceiling of ₹1,500 per month per apprentice) paid straight into the candidate's account via DBT.",
    eligibility: "Must be an Indian national with basic academic qualifications matching the technical apprentice trade criteria.",
    applicationProcess: "Candidates register profile summaries on the Apprenticeship India digital hub, where they filter and apply for open company positions.",
    requiredDocuments: ["Aadhaar Card", "ITI / Diploma / Graduation Marksheets", "Bank Account Proof"],
    officialUrl: "https://www.apprenticeshipindia.gov.in",
    startDate: "2016-08-19",
    endDate: null,
    ministry: "Ministry of Skill Development and Entrepreneurship",
    schemeType: "Central Sector",
    occupationTags: ["Student", "Unemployed"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["10th Pass", "12th Pass", "Graduate"],
    ageMin: 14,
    ageMax: 35,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "stand-up-india-scheme",
    title: "Stand-Up India Scheme",
    description: "A business loan program designed to promote entrepreneurship at the grassroots level among scheduled castes, scheduled tribes, and women pioneers.",
    category: "Business & Entrepreneurship",
    targetGroup: "SC, ST, and Women entrepreneurs setting up fresh manufacturing, services, or agri-allied greenfield projects.",
    benefits: "Composite bank loans between ₹10 Lakh and ₹1 Crore covering up to 75% of the project layout costs, featuring concessional interest parameters.",
    eligibility: "Must be a woman or belong to SC/ST category. The enterprise must be a greenfield project (first-time venture). For non-individual setups, 51% stake must rest with an SC/ST or woman.",
    applicationProcess: "Can be applied directly at scheduled bank desks, through the Stand-Up India digital marketplace portal, or via SIDBI counselors.",
    requiredDocuments: ["Aadhaar Card", "Caste Certificate (if SC/ST)", "Business Project Report", "Company Incorporation Proof", "Income Tax Returns Profile"],
    officialUrl: "https://www.standupmitra.in",
    startDate: "2016-04-05",
    endDate: "2027-03-31",
    ministry: "Ministry of Finance",
    schemeType: "Central Sector",
    occupationTags: ["Entrepreneur", "Business Owner", "Self-Employed"],
    stateTags: ["All"],
    genderTags: ["Female", "All"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 75,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "pradhan-mantri-bhartiya-jan-aushadhi-pariyojana-pmbjp",
    title: "Pradhan Mantri Bhartiya Jan Aushadhi Pariyojana (PMBJP)",
    description: "A high-impact public healthcare initiative to make high-quality generic medicines available to everyone at highly affordable prices through dedicated retail outlets.",
    category: "Health & Medical",
    targetGroup: "All citizens, particularly lower-income families who struggle with massive out-of-pocket healthcare expenses.",
    benefits: "Access to therapeutic generic medicines, surgical items, and nutraceutical consumables that are 50% to 90% cheaper than matching branded variants.",
    eligibility: "Open to any resident citizen needing healthcare consumables. No specific income verification bounds are enforced at point-of-sale.",
    applicationProcess: "Walk-in access to any authorized Jan Aushadhi Kendra across India with a valid medical prescription.",
    requiredDocuments: ["Doctor Prescription"],
    officialUrl: "https://janaushadhi.gov.in",
    startDate: "2008-11-25",
    endDate: null,
    ministry: "Ministry of Chemicals and Fertilizers",
    schemeType: "Central Sector",
    occupationTags: ["All"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 0,
    ageMax: 120,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "pm-yasasvi-scholarship-scheme",
    title: "PM YASASVI Scholarship Scheme",
    description: "A major merit-based academic scholarship for marginalized students across the country to enable them to complete senior education tracks.",
    category: "Education",
    targetGroup: "Students belonging to Other Backward Classes (OBC), Economically Backward Classes (EBC), and De-Notified Tribes (DNT).",
    benefits: "Provides top-class educational infrastructure scholarship grants up to ₹75,000 per year for Class 9 and 10, and up to ₹1,25,000 per year for Class 11 and 12 students.",
    eligibility: "Must be an Indian student studying in identified top schools. Combined annual family income cannot exceed specified caps.",
    applicationProcess: "Applications must be submitted electronically via the National Scholarship Portal (NSP), followed by institutional verified checks.",
    requiredDocuments: ["Aadhaar Card", "Income Certificate", "Caste Certificate (OBC/EBC/DNT)", "Previous Class Progress Marksheet", "Bank Account Passbook"],
    officialUrl: "https://scholarships.gov.in",
    startDate: "2022-05-25",
    endDate: null,
    ministry: "Ministry of Social Justice and Empowerment",
    schemeType: "Centrally Sponsored",
    occupationTags: ["Student"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["Under 10th", "10th Pass"],
    ageMin: 13,
    ageMax: 20,
    incomeMin: "0",
    incomeMax: "250000",
    isActive: true
  },
  {
    slug: "indira-gandhi-national-old-age-pension-scheme-ignoaps",
    title: "Indira Gandhi National Old Age Pension Scheme (IGNOAPS)",
    description: "A core component of the National Social Assistance Programme providing critical financial monthly pension buffers to elderly citizens.",
    category: "Social Security & Pension",
    targetGroup: "Senior citizens living inside households classified below the national poverty threshold line.",
    benefits: "Monthly pension of ₹200 for citizens up to 79 years old, which steps up to ₹500 monthly once they hit 80 years old, often supplemented by local matching state payouts.",
    eligibility: "Must be a citizen matching age parameters and whose family holds a valid Below Poverty Line (BPL) ration registration tracking card.",
    applicationProcess: "Applications are submitted through the local Social Welfare Office, Gram Panchayat administration desk, or Urban Local Bodies.",
    requiredDocuments: ["Aadhaar Card", "BPL Ration Card", "Age Verification Proof (Birth Certificate/Voter Card)", "Bank Passbook"],
    officialUrl: "https://nsap.nic.in",
    startDate: "1995-08-15",
    endDate: null,
    ministry: "Ministry of Rural Development",
    schemeType: "Centrally Sponsored",
    occupationTags: ["Unemployed", "Laborer"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 60,
    ageMax: 120,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "deendayal-antyodaya-yojana-national-rural-livelihoods-mission-day-nrlm",
    title: "DAY-NRLM (National Rural Livelihoods Mission)",
    description: "A poverty alleviation project focused on organizing poor rural women into structured Self-Help Groups (SHGs) to build sustainable livelihood strategies.",
    category: "Skill Development & Employment",
    targetGroup: "Rural women who belong to marginalized and economically backward social segments.",
    benefits: "Provides Revolving Funds (RF) and Community Investment Funds (CIF), institutional capacity building training, and interest subvention benefits on bank credit up to ₹3 Lakh.",
    eligibility: "At least one able-bodied female member from target poor rural households who forms or joins an affinity SHG cluster.",
    applicationProcess: "Managed locally by state livelihood mission fields, block coordinators, and regional SHG federation networks.",
    requiredDocuments: ["Aadhaar Card", "Ration Card", "Group Bank Account Details", "Passport Size Photos"],
    officialUrl: "https://aajeevika.gov.in",
    startDate: "2011-06-03",
    endDate: null,
    ministry: "Ministry of Rural Development",
    schemeType: "Centrally Sponsored",
    occupationTags: ["Self-Employed", "Artisan", "Farmer", "Unemployed"],
    stateTags: ["All"],
    genderTags: ["Female"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 65,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "pradhan-mantri-matru-vandana-yojana-pmmvy",
    title: "Pradhan Mantri Matru Vandana Yojana (PMMVY)",
    description: "A conditional cash transfer maternity benefit program providing partial compensation for wage loss to ensure adequate nutrition and rest before and after child delivery.",
    category: "Women & Child Development",
    targetGroup: "Pregnant Women and Lactating Mothers (PW&LM) during their first and second live births.",
    benefits: "Direct Cash Benefit of ₹5,000 paid in two installments for the first child, and an enhanced payout of ₹6,000 for the second child provided the newborn is a girl.",
    eligibility: "All pregnant women and lactating mothers, excluding those who are in regular employment with Central/State Governments or Public Sector Undertakings.",
    applicationProcess: "Registration can be filed online using the PMMVY citizen login or via local Anganwadi Centres (AWC) or authorized healthcare structures.",
    requiredDocuments: ["Aadhaar Card of Mother", "Aadhaar Card of Husband", "Mother and Child Protection (MCP) Card", "Bank Passbook linked to Aadhaar", "Child Birth Certificate (for latter installments)"],
    officialUrl: "https://pmmvy.wcd.gov.in",
    startDate: "2017-01-01",
    endDate: null,
    ministry: "Ministry of Women and Child Development",
    schemeType: "Centrally Sponsored",
    occupationTags: ["Unemployed", "Domestic Worker", "Laborer"],
    stateTags: ["All"],
    genderTags: ["Female"],
    educationTags: ["All"],
    ageMin: 19,
    ageMax: 50,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "credit-guarantee-fund-trust-for-micro-and-small-enterprises-cgtmse",
    title: "Credit Guarantee Fund Trust Scheme (CGTMSE)",
    description: "A business backing framework set up to make collateral-free credit flow to the micro and small enterprise (MSE) industry segments.",
    category: "Business & Entrepreneurship",
    targetGroup: "New and existing micro and small business entities needing debt funding assistance.",
    benefits: "Provides credit guarantee coverage up to 75% or 85% for business loans and working capital overdraft facilities up to ₹5 Crore without demanding physical security collateral.",
    eligibility: "Eligible micro and small enterprises running manufacturing or service operations. Excludes retail trading tracks, educational structures, and agriculture setups.",
    applicationProcess: "Entrepreneurs apply for business loans at Member Lending Institutions (Scheduled Banks, Regional Rural Banks, NBFCs) which request guarantee cover via the CGTMSE backend.",
    requiredDocuments: ["Detailed Project Report (DPR)", "Udyam Registration Certificate", "Business Entity Pan Card", "ITR Records & Balance Sheets"],
    officialUrl: "https://www.cgtmse.in",
    startDate: "2000-08-01",
    endDate: null,
    ministry: "Ministry of Micro, Small and Medium Enterprises",
    schemeType: "Central Sector",
    occupationTags: ["Business Owner", "Entrepreneur", "Self-Employed"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 70,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "pradhan-mantri-matsya-sampada-yojana-pmmsy",
    title: "Pradhan Mantri Matsya Sampada Yojana (PMMSY)",
    description: "A flagship program designed to turn around the fisheries ecosystem by addressing critical layout gaps across infrastructure, trace capability, production value, and harvest management.",
    category: "Agriculture",
    targetGroup: "Fishers, fish farmers, fish workers, vendors, self-help groups, and fisheries entrepreneurs.",
    benefits: "Subsidies ranging from 40% (for general category) up to 60% (for SC/ST/Women beneficiaries) for setup inputs, deep-sea vessels, cold storage equipment, and biofloc ponds.",
    eligibility: "Any individual or collective group directly involved in marine or inland aquaculture operations matching the state fisheries department guidelines.",
    applicationProcess: "Beneficiaries must submit an extensive project proposal tracking details to district fisheries offices or via state portal pathways.",
    requiredDocuments: ["Aadhaar Card", "Fisherman Identity Card / Group Registration Proof", "Land Ownership / Lease Documents for Water Body", "Detailed Project Estimate Plan"],
    officialUrl: "https://pmmsy.dof.gov.in",
    startDate: "2020-05-20",
    endDate: null,
    ministry: "Ministry of Fisheries, Animal Husbandry and Dairying",
    schemeType: "Centrally Sponsored",
    occupationTags: ["Fisherman", "Farmer", "Entrepreneur"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 70,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "soil-health-card-scheme",
    title: "Soil Health Card Scheme",
    description: "An agricultural support program aimed at helping farmers understand the precise nutritional imbalances of their soil to pick customized chemical fertilizer inputs.",
    category: "Agriculture",
    targetGroup: "All landholding farmers throughout the country.",
    benefits: "Provides a printed Soil Health Card containing status readings of 12 critical macro and micronutrients along with specific dosage guidelines tailored to chosen crops.",
    eligibility: "All farmers owning cultivable agricultural land blocks inside participating states.",
    applicationProcess: "Local agriculture department personnel systematically gather samples right from the farm fields for testing at designated public soil testing laboratories.",
    requiredDocuments: ["Land Record Copy (Patta/Chitta)", "Aadhaar Card Copy", "Mobile Number Profile"],
    officialUrl: "https://soilhealth.dac.gov.in",
    startDate: "2015-02-19",
    endDate: null,
    ministry: "Ministry of Agriculture and Farmers Welfare",
    schemeType: "Centrally Sponsored",
    occupationTags: ["Farmer"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 100,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "ayushman-bharat-digital-mission-abdm",
    title: "Ayushman Bharat Digital Mission (ABDM)",
    description: "An initiative aimed at developing a unified digital health backbone for India, linking electronic health registries, medical histories, and clinical institutions seamlessly.",
    category: "Health & Medical",
    targetGroup: "All individual citizens seeking streamlined maintenance of health profiles.",
    benefits: "Enables creation of a safe 14-digit Ayushman Bharat Health Account (ABHA) link which acts as a free encrypted portal to safely share medical reports across verified testing centers and hospitals.",
    eligibility: "Open to every living resident citizen of India voluntarily signing up for a streamlined electronic record framework.",
    applicationProcess: "Citizens can generate their unique ABHA card profile in under two minutes online using the official ABDM web app, or via participating hospital desks.",
    requiredDocuments: ["Aadhaar Card or Driving License", "Mobile Number linked with Aadhaar Identification"],
    officialUrl: "https://abdm.gov.in",
    startDate: "2021-09-27",
    endDate: null,
    ministry: "Ministry of Health and Family Welfare",
    schemeType: "Central Sector",
    occupationTags: ["All"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 0,
    ageMax: 120,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  }
];