export const seedSchemesBatch3 = [
  {
    slug: "pradhan-mantri-awas-yojana-gramin-pmay-g",
    title: "Pradhan Mantri Awas Yojana - Gramin (PMAY-G)",
    description: "A flagship housing initiative aimed at providing a pucca house with basic amenities to all houseless householders and those households living in dilapidated houses in rural areas.",
    category: "Housing & Urban Development",
    targetGroup: "Rural poor, houseless families, and households living in zero, one, or two-room kucha houses based on SECC 2011 data.",
    benefits: "Financial assistance of ₹1.2 Lakh in plains and ₹1.3 Lakh in hilly, difficult areas, and integrated convergence of up to ₹95 days of unskilled labor wages under MGNREGA plus ₹12,000 for toilet construction.",
    eligibility: "Rural families listed under the SECC 2011 permanent waitlist, falling under SC/ST, freed bonded laborers, non-SC/ST minorities, and widows of defense personnel.",
    applicationProcess: "Identification and selection are automatically completed through Gram Sabha validation of SECC 2011 data. Geo-tagging of existing structures is done via the AwaasApp.",
    requiredDocuments: ["Aadhaar Card", "Bank Account Details", "MGNREGA Job Card Number", "Swachh Bharat Mission (SBM) Registration Number"],
    officialUrl: "https://pmayg.nic.in",
    startDate: "2016-04-01",
    endDate: null,
    ministry: "Ministry of Rural Development",
    schemeType: "Centrally Sponsored",
    occupationTags: ["Farmer", "Laborer", "Unemployed"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 100,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "jal-jeevan-mission-jjm",
    title: "Jal Jeevan Mission (JJM)",
    description: "A massive central infrastructure mission aiming to provide safe and adequate drinking water through individual Functional Household Tap Connections (FHTCs) to all households in rural India.",
    category: "Utility & Energy",
    targetGroup: "All rural households, schools, Anganwadi centers, and public institutional community buildings.",
    benefits: "Provision of clean, regular, and safe drinking water directly via domestic tap connections at a minimum service level of 55 liters per capita per day.",
    eligibility: "Any domestic household located within rural habitations across all states and Union Territories.",
    applicationProcess: "Implemented through community-led Village Water and Sanitation Committees (VWSC) or Pani Samitis. Individual application forms are rarely required as deployment is community-wide.",
    requiredDocuments: ["Property Tax Receipt or Household ID Proof", "Aadhaar Card"],
    officialUrl: "https://jaljeevanmission.gov.in",
    startDate: "2019-08-15",
    endDate: null,
    ministry: "Ministry of Jal Shakti",
    schemeType: "Centrally Sponsored",
    occupationTags: ["All", "Farmer", "Laborer"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 0,
    ageMax: 120,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "pm-surya-ghar-muft-bijli-yojana",
    title: "PM-Surya Ghar: Muft Bijli Yojana",
    description: "A flagship sustainable energy initiative launched to provide up to 300 units of free electricity per month to one crore households in India through rooftop solar setups.",
    category: "Utility & Energy",
    targetGroup: "Residential households seeking to transition to solar energy and reduce electricity expenses.",
    benefits: "Direct central subsidy up to ₹78,000 for a 3kW system. It reduces monthly domestic grid electricity costs and allows households to earn income by selling surplus power back to DISCOMs.",
    eligibility: "Must be an Indian citizen owning a residential house with a structurally sound roof suitable for solar installation, holding an active consumer electricity grid connection.",
    applicationProcess: "Applications are processed electronically through the National Rooftop Solar Portal. Users select local registered DISCOM vendors and apply for structural feasibility approvals online.",
    requiredDocuments: ["Electricity Bill (Recent 6 Months)", "Roof Ownership Certificate or Land Deed", "Aadhaar Card", "Bank Passbook Copy"],
    officialUrl: "https://pmsuryaghar.gov.in",
    startDate: "2024-02-15",
    endDate: null,
    ministry: "Ministry of New and Renewable Energy",
    schemeType: "Central Sector",
    occupationTags: ["All", "Salaried", "Self-Employed", "Business Owner"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 65,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "lakhpati-didi-scheme",
    title: "Lakhpati Didi Scheme",
    description: "An economic empowerment initiative targeting women members of Self-Help Groups (SHGs) to help them build micro-enterprises and secure an annual net household income of at least ₹1 Lakh.",
    category: "Women & Child Development",
    targetGroup: "Rural women organized within structured community-level Self-Help Groups.",
    benefits: "Access to structural technical and financial literacy skill training (plumbing, drone operation, LED bulb making, tailoring), market linkage acceleration, and access to collateral-free institutional loans up to ₹20 Lakh via SHG frameworks.",
    eligibility: "Must be a female citizen of India and an active member of a registered woman Self-Help Group that has maintained good credit cycles for a minimum period.",
    applicationProcess: "Managed locally at the block level through the State Rural Livelihoods Mission (SRLM) operators. Women submit micro-investment business project plans via their respective SHG cluster federations.",
    requiredDocuments: ["Aadhaar Card", "SHG Membership Certificate", "Ration Card", "Bank Account Passbook", "Passport Size Photograph"],
    officialUrl: "https://lakhpatididi.gov.in",
    startDate: "2023-08-15",
    endDate: null,
    ministry: "Ministry of Rural Development",
    schemeType: "Centrally Sponsored",
    occupationTags: ["Self-Employed", "Artisan", "Farmer", "Unemployed"],
    stateTags: ["All"],
    genderTags: ["Female"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 65,
    incomeMin: "0",
    incomeMax: "100000",
    isActive: true
  },
  {
    slug: "kisan-credit-card-kcc-scheme",
    title: "Kisan Credit Card (KCC) Scheme",
    description: "A credit framework designed to offer farmers flexible, timely, and single-window short-term credit from the formal banking ecosystem to fulfill their cultivation, crop harvest, and domestic consumption demands.",
    category: "Agriculture",
    targetGroup: "All categories of farmers, including individual/joint cultivators, tenant farmers, sharecroppers, and self-help groups of farmers.",
    benefits: "Provides short-term credit lines with an effective low interest rate of 4% (after timely repayment subventions). Includes built-in crop insurance coverage and credit tracking flexibilities via ATM-enabled RuPay cards.",
    eligibility: "All resident farmers, including those engaged in animal husbandry, dairy production, poultry, and inland fisheries operations.",
    applicationProcess: "Applicants can apply directly online through institutional banking portals or submit a simplified single-page KCC application form at the nearest commercial or regional rural bank.",
    requiredDocuments: ["Aadhaar Card", "Land Record Documents (Pattas/7-12 Extracts)", "Sowing Certificate issued by Local Revenue Officials", "Passport Size Photograph"],
    officialUrl: "https://www.nabard.org",
    startDate: "1998-08-01",
    endDate: null,
    ministry: "Ministry of Agriculture and Farmers Welfare",
    schemeType: "Central Sector",
    occupationTags: ["Farmer"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 75,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "pradhan-mantri-shram-yogi-maan-dhan-pm-sym",
    title: "Pradhan Mantri Shram Yogi Maan-dhan (PM-SYM)",
    description: "A voluntary and contributory pension scheme designed to provide old-age social security to workers operating within unorganized sectors who are excluded from formal payroll structures.",
    category: "Social Security & Pension",
    targetGroup: "Unorganized workers such as street vendors, head loaders, brick kiln workers, cobblers, ragpickers, domestic helpers, and agricultural laborers.",
    benefits: "Assured minimum monthly pension of ₹3,000 after attaining the age of 60 years. If the subscriber dies, the spouse is entitled to receive 50% of the pension as a family pension.",
    eligibility: "Must be an unorganized worker aged between 18 and 40 years. Monthly income must be ₹15,000 or less, and the subscriber must not be an income taxpayer or an EPFO/ESIC/NPS member.",
    applicationProcess: "Enrolment can be completed online on the Shram Yogi portal or by visiting any nearby Common Service Centre (CSC) with bank auto-debit consent details.",
    requiredDocuments: ["Aadhaar Card", "Savings Bank Account Passbook or Cancelled Cheque", "Active Mobile Number"],
    officialUrl: "https://maandhan.in",
    startDate: "2019-02-15",
    endDate: null,
    ministry: "Ministry of Labour and Employment",
    schemeType: "Central Sector",
    occupationTags: ["Laborer", "Domestic Worker", "Street Vendor", "Driver"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 40,
    incomeMin: "0",
    incomeMax: "180000",
    isActive: true
  },
  {
    slug: "pradhan-mantri-kisan-maandhan-yojana-pm-kmy",
    title: "Pradhan Mantri Kisan Maandhan Yojana (PM-KMY)",
    description: "A voluntary, contributory old-age pension scheme tailored specifically for small and marginal farmers to sustain their livelihoods during retirement.",
    category: "Social Security & Pension",
    targetGroup: "Small and Marginal Farmers (SMFs) across India.",
    benefits: "Guaranteed minimum monthly pension of ₹3,000 upon reaching 60 years of age. The Central Government matches the subscriber's monthly premium contribution equally.",
    eligibility: "Farmers owning cultivable land up to 2 hectares, aged between 18 and 40 years. Must not be covered under other statutory social security platforms.",
    applicationProcess: "Eligical farmers apply at local Common Service Centres (CSCs) or self-register on the PM-KMY web portal, with an option to deduct monthly premiums directly from their PM-KISAN benefits.",
    requiredDocuments: ["Aadhaar Card", "Land Possession Document Copy", "Savings Bank Account Details", "Mobile Number"],
    officialUrl: "https://maandhan.in",
    startDate: "2019-09-12",
    endDate: null,
    ministry: "Ministry of Agriculture and Farmers Welfare",
    schemeType: "Central Sector",
    occupationTags: ["Farmer"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 40,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "pm-janjati-adivasi-nyaya-maha-abhiyan-pm-janman",
    title: "PM Janjati Adivasi Nyaya Maha Abhiyan (PM JANMAN)",
    description: "A highly specialized intervention mission designed to deliver comprehensive social, infrastructural, and economic welfare protections to Particularly Vulnerable Tribal Groups (PVTGs).",
    category: "Social Security & Pension",
    targetGroup: "Particularly Vulnerable Tribal Groups (PVTGs) residing across tribal blocks and remote hamlets.",
    benefits: "Ensures delivery of 11 critical interventions across line ministries, including fast-tracked pucca housing construction, solar power provisioning, clean tap water pipelines, mobile medical vans, and skill training.",
    eligibility: "Families and communities formally categorized under the 75 recognized Particularly Vulnerable Tribal Groups (PVTGs) in India.",
    applicationProcess: "Monitored and driven directly by administrative field saturation surveys. Dynamic mobile camps are deployed by local district magistrates to register beneficiaries.",
    requiredDocuments: ["ST Community Certificate (PVTG Sub-category)", "Aadhaar Card", "Ration Card"],
    officialUrl: "https://tribal.nic.in",
    startDate: "2023-11-15",
    endDate: null,
    ministry: "Ministry of Tribal Affairs",
    schemeType: "Central Sector",
    occupationTags: ["Laborer", "Artisan", "Farmer", "Unemployed"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 0,
    ageMax: 120,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "beti-bachao-beti-padhao-bbbp",
    title: "Beti Bachao Beti Padhao (BBBP)",
    description: "A major multi-sectoral national campaign intended to check declining child sex ratios, prevent female foeticide, and ensure the survival, protection, and complete higher education of the girl child.",
    category: "Women & Child Development",
    targetGroup: "Girls, mothers, and public communities across identified districts with low child sex ratios.",
    benefits: "Institutional support for girl child protection, dedicated gender-segregated school toilets, community awareness fellowships, and tracking mechanisms for systemic educational retention.",
    eligibility: "Open broadly to families with girl children in India, with targeted structural provisions focused on school-going girls and mothers.",
    applicationProcess: "Operates as a high-visibility structural advocacy policy. Direct localized financial grants are integrated with matching schemes like Sukanya Samriddhi Yojana (SSY).",
    requiredDocuments: ["Birth Certificate of Girl Child", "Aadhaar Card of Parents", "Domicile Verification Proof"],
    officialUrl: "https://wcd.gov.in",
    startDate: "2015-01-22",
    endDate: null,
    ministry: "Ministry of Women and Child Development",
    schemeType: "Centrally Sponsored",
    occupationTags: ["Student"],
    stateTags: ["All"],
    genderTags: ["Female"],
    educationTags: ["All"],
    ageMin: 0,
    ageMax: 18,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "deendayal-antyodaya-yojana-national-urban-livelihoods-mission-day-nulm",
    title: "DAY-NULM (National Urban Livelihoods Mission)",
    description: "A targeted urban poverty alleviation framework aimed at reducing poverty and vulnerability of urban poor households by enabling them to access gainful self-employment and skilled wage employment opportunities.",
    category: "Skill Development & Employment",
    targetGroup: "Urban poor, street vendors, homeless individuals, and marginalized urban laborers.",
    benefits: "Interest subsidy of 5% to 7% on bank credit for setting up micro-enterprises, free urban skill development training modules, setting up of multi-utility urban homeless shelters, and formal vendor zoning infrastructure.",
    eligibility: "Urban poor residents living in urban areas, with priority execution targets assigned to women, minorities, and disabled citizens.",
    applicationProcess: "Applicants apply through local Municipal Corporations, Urban Local Bodies (ULBs), or designated urban community resource centers.",
    requiredDocuments: ["Urban BPL Card or Income Verification Certificate", "Aadhaar Card", "Bank Passbook Copy", "Passport Size Photos"],
    officialUrl: "https://nulm.gov.in",
    startDate: "2013-09-24",
    endDate: null,
    ministry: "Ministry of Housing and Urban Affairs",
    schemeType: "Centrally Sponsored",
    occupationTags: ["Street Vendor", "Laborer", "Unemployed", "Artisan"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 60,
    incomeMin: "0",
    incomeMax: "300000",
    isActive: true
  },
  {
    slug: "startup-india-initiative",
    title: "Startup India Initiative",
    description: "A flagship developmental program designed to construct a robust startup ecosystem in India, driving sustainable economic expansion and generating scalable employment avenues.",
    category: "Business & Entrepreneurship",
    targetGroup: "Innovators, technology disruptors, early-stage business founders, and registered commercial entities.",
    benefits: "Provides formal recognition by DPIIT, 3 years of income tax exemptions, relaxed procurement compliances in public tenders, capital gains tax exemptions, fast-tracked patent examinations, and access to seed funding pipelines.",
    eligibility: "An entity incorporated as a private limited company, partnership, or LLP within India for less than 10 years, with annual turnover not exceeding ₹100 Crore.",
    applicationProcess: "Founders log a digital business profile on the Startup India digital portal along with a brief write-up on their innovation or business scalability parameters to receive recognition.",
    requiredDocuments: ["Certificate of Incorporation / Registration", "Brief Concept Note on Innovation / Market Scalability", "Patent or Trademark Records (Optional)"],
    officialUrl: "https://www.startupindia.gov.in",
    startDate: "2016-01-16",
    endDate: null,
    ministry: "Ministry of Commerce and Industry",
    schemeType: "Central Sector",
    occupationTags: ["Entrepreneur", "Business Owner"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["Graduate", "All"],
    ageMin: 18,
    ageMax: 70,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "senior-citizens-savings-scheme-scss",
    title: "Senior Citizens Savings Scheme (SCSS)",
    description: "A high-yielding, government-backed small savings and retirement security scheme designed to offer regular income safety to senior citizens.",
    category: "Finance & Banking",
    targetGroup: "Retirees and senior citizens seeking low-risk quarterly income options.",
    benefits: "Offers high interest rates (compounded quarterly) backed by sovereign guarantee. Investments qualify for tax deductions under Section 80C, with flexible maturity extension allowances.",
    eligibility: "Individuals who have attained the age of 60 years, or individuals aged 55-60 years who have retired on superannuation or VRS under specific conditions.",
    applicationProcess: "Accounts can be opened physically at any commercial bank branch or post office across the country with a lump-sum check deposit.",
    requiredDocuments: ["Aadhaar Card", "PAN Card", "Age Proof Documents (Voter Card / Passport)", "Retirement Benefit Disbursal Proofs (for VRS applicants)"],
    officialUrl: "https://www.nsiindia.gov.in",
    startDate: "2004-08-02",
    endDate: null,
    ministry: "Ministry of Finance",
    schemeType: "Central Sector",
    occupationTags: ["Unemployed", "All"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 60,
    ageMax: 100,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "samagra-shiksha-abhiyan",
    title: "Samagra Shiksha Abhiyan",
    description: "An overarching integrated school education program extending from pre-school to class 12, aiming to ensure inclusive and equitable quality education throughout the country.",
    category: "Education",
    targetGroup: "School children, teachers, and basic infrastructure educational institutions across India.",
    benefits: "Provides free text-books, uniforms for girls and SC/ST/BPL boys, infrastructure upgrades (ICT labs, science libraries), digital learning aids, and dedicated safety sports transport funds.",
    eligibility: "All students enrolled in government and government-aided institutional school tracks from pre-primary to higher secondary levels.",
    applicationProcess: "Administered structurally via state education departments and local school management committees (SMC). Students receive programmatic benefits automatically upon public school enrollment.",
    requiredDocuments: ["Student Aadhar Card Proof", "School Admission Record", "Community / Caste Certificate (if claiming specific allowances)"],
    officialUrl: "https://samagra.education.gov.in",
    startDate: "2018-04-01",
    endDate: null,
    ministry: "Ministry of Education",
    schemeType: "Centrally Sponsored",
    occupationTags: ["Student"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["Under 10th", "10th Pass", "12th Pass"],
    ageMin: 4,
    ageMax: 18,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "indira-gandhi-national-widow-pension-scheme-ignwps",
    title: "Indira Gandhi National Widow Pension Scheme (IGNWPS)",
    description: "A structural social security sub-scheme under the National Social Assistance Programme designed to extend direct monthly financial pensions to destitute widows.",
    category: "Social Security & Pension",
    targetGroup: "Widows living within families classified below the national poverty line.",
    benefits: "Provides a guaranteed direct monthly cash pension of ₹300 for beneficiaries up to 79 years old, which upgrades to ₹500 monthly upon attaining 80 years of age.",
    eligibility: "Must be a female resident citizen of India, a widow aged between 40 and 79 years, whose household is registered under the active BPL waitlist index.",
    applicationProcess: "Applications must be physically prepared and submitted to the local block development officer, Gram Panchayat office, or municipal desk.",
    requiredDocuments: ["Aadhaar Card", "Husband's Death Certificate", "BPL Ration Card Record", "Bank Passbook Copy"],
    officialUrl: "https://nsap.nic.in",
    startDate: "2009-02-01",
    endDate: null,
    ministry: "Ministry of Rural Development",
    schemeType: "Centrally Sponsored",
    occupationTags: ["Unemployed", "Laborer", "Domestic Worker"],
    stateTags: ["All"],
    genderTags: ["Female"],
    educationTags: ["All"],
    ageMin: 40,
    ageMax: 79,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "pm-poshan-shakti-nirman-mid-day-meal",
    title: "PM POSHAN (Pradhan Mantri Poshan Shakti Nirman)",
    description: "A massive central nutritional security intervention in schools, formerly known as the Mid-Day Meal Scheme, aimed at enhancing the nutritional status of school-age children while simultaneously boosting school enrollment and retention.",
    category: "Education",
    targetGroup: "Children studying in elementary classes of government, government-aided, local body, and alternative education centers.",
    benefits: "Provision of free cooked, hot, nutritious meals every school working day matching prescribed calorie and protein nutrition profiles (minimum 450 calories for primary levels).",
    eligibility: "All children studying in Class 1 to 8 across participating government and institutional aided campuses.",
    applicationProcess: "Integrated structurally within the school operational frameworks. No individual application paperwork is necessary for students.",
    requiredDocuments: ["School Student Identification Record"],
    officialUrl: "https://pmposhan.education.gov.in",
    startDate: "1995-08-15",
    endDate: null,
    ministry: "Ministry of Education",
    schemeType: "Centrally Sponsored",
    occupationTags: ["Student"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["Under 10th"],
    ageMin: 6,
    ageMax: 14,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  }
];