export const seedSchemes = [
  {
    slug: "pradhan-mantri-kisan-samman-nidhi-pm-kisan",
    title: "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)",
    description: "A central sector scheme providing income support to all landholding farmers' families across the country to supplement their financial needs for procuring various inputs related to agriculture and allied activities.",
    category: "Agriculture",
    targetGroup: "Landholding Farmer Families",
    benefits: "Direct financial benefit of ₹6,000 per year per family, payable in three equal installments of ₹2,000 every four months directly into the bank accounts of the beneficiaries.",
    eligibility: "All landholding farmers' families who own cultivable land holding in their names. Excludes institutional landholders, high-income taxpayers, and retired/serving government employees.",
    applicationProcess: "Farmers can apply online via the PM-KISAN portal, through the PM-KISAN mobile app, or by visiting the nearest Common Service Centre (CSC) or local revenue/agriculture officer.",
    requiredDocuments: ["Aadhaar Card", "Land Ownership Documents (Khatauni)", "Bank Account Passbook", "Identity Proof"],
    officialUrl: "https://pmkisan.gov.in",
    startDate: "2018-12-01",
    endDate: null,
    ministry: "Ministry of Agriculture and Farmers Welfare",
    schemeType: "Central Sector",
    occupationTags: ["Farmer", "Self-Employed"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 100,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "ayushman-bharat-pradhan-mantri-jan-arogya-yojana-pmjay",
    title: "Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana (PM-JAY)",
    description: "The world's largest health insurance/assurance scheme fully financed by the government, aiming to provide secondary and tertiary care hospitalization benefits to poor and vulnerable families.",
    category: "Health & Medical",
    targetGroup: "Poor, vulnerable rural families and identified occupational categories of urban workers' families based on SECC data.",
    benefits: "A health cover of ₹5 Lakh per family per year for secondary and tertiary care hospitalization across empanelled public and private hospitals.",
    eligibility: "Families listed in the Socio-Economic Caste Census (SECC) 2011 database, including families with no adult/male earning members, landless households, and informal workers.",
    applicationProcess: "Individuals can check eligibility on the PM-JAY online portal or app. Eligible beneficiaries receive an Ayushman Card at empanelled hospitals or CSCs.",
    requiredDocuments: ["Aadhaar Card", "Ration Card", "Identity Proof", "SECC Letter"],
    officialUrl: "https://pmjay.gov.in",
    startDate: "2018-09-23",
    endDate: null,
    ministry: "Ministry of Health and Family Welfare",
    schemeType: "Centrally Sponsored",
    occupationTags: ["Laborer", "Unemployed", "Domestic Worker", "Artisan"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 0,
    ageMax: 120,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "sukanya-samriddhi-yojana-ssy",
    title: "Sukanya Samriddhi Yojana (SSY)",
    description: "A small deposit savings scheme explicitly designed for the benefit of a girl child as part of the 'Beti Bachao Beti Padhao' campaign to meet education and marriage expenses.",
    category: "Women & Child Development",
    targetGroup: "Girl children below the age of 10 years.",
    benefits: "High-interest savings account (compounded annually) with tax benefits under Section 80C. Complete maturity amount is tax-free after 21 years or upon marriage after turning 18.",
    eligibility: "Can be opened by the natural or legal guardian in the name of a girl child who is an Indian citizen. Maximum of two accounts per family (three in case of twins/triplets).",
    applicationProcess: "The account can be opened physically at any authorized post office or branches of commercial banks handling public provident funds.",
    requiredDocuments: ["Girl Child Birth Certificate", "Guardian Identity Proof", "Guardian Address Proof", "Aadhaar Card of Guardian"],
    officialUrl: "https://www.indiapost.gov.in",
    startDate: "2015-01-22",
    endDate: null,
    ministry: "Ministry of Finance",
    schemeType: "Central Sector",
    occupationTags: ["Student"],
    stateTags: ["All"],
    genderTags: ["Female"],
    educationTags: ["All"],
    ageMin: 0,
    ageMax: 10,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "pradhan-mantri-mudra-yojana-pmmy",
    title: "Pradhan Mantri Mudra Yojana (PMMY)",
    description: "A flagship scheme enabling micro and small enterprises to access collateral-free institutional loans for business setup, expansion, and modernization.",
    category: "Business & Entrepreneurship",
    targetGroup: "Non-corporate, non-farm small/micro enterprises, shopkeepers, traders, and startups.",
    benefits: "Collateral-free business loans split into three categories: Shishu (up to ₹50,000), Kishor (₹50,001 to ₹5 Lakh), and Tarun (₹5,00,001 to ₹10 Lakh).",
    eligibility: "Any Indian citizen who has a non-farm business plan for income-generating activities such as manufacturing, processing, trading, or the service sector.",
    applicationProcess: "Applicants can apply online through the Udyam Mitra portal or approach public sector banks, private banks, regional rural banks, or NBFCs.",
    requiredDocuments: ["Business Plan/Proposal", "Identity Proof", "Address Proof", "Passport Size Photos", "Business Address Proof", "Aadhaar Card"],
    officialUrl: "https://www.mudra.org.in",
    startDate: "2015-04-08",
    endDate: null,
    ministry: "Ministry of Finance",
    schemeType: "Central Sector",
    occupationTags: ["Entrepreneur", "Business Owner", "Self-Employed"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 65,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "mahatma-gandhi-national-rural-employment-guarantee-act-mgnrega",
    title: "Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)",
    description: "A social security measure that guarantees the right to work by providing at least 100 days of wage employment in a financial year to rural households.",
    category: "Employment & Labor",
    targetGroup: "Adult members of rural households willing to do unskilled manual work.",
    benefits: "Guaranteed 100 days of paid manual labor. Unemployment allowance is paid if work is not provided within 15 days of application. Wages are directly paid into bank accounts.",
    eligibility: "Must be a citizen of India residing in a rural area, aged 18 or above, and volunteer for local unskilled manual labor.",
    applicationProcess: "Apply to the local Gram Panchayat using a prescribed form or orally. A Job Card is issued within 15 days of registration.",
    requiredDocuments: ["Aadhaar Card", "Bank Account Details", "Ration Card", "Passport Size Photograph"],
    officialUrl: "https://nrega.nic.in",
    startDate: "2006-02-02",
    endDate: null,
    ministry: "Ministry of Rural Development",
    schemeType: "Centrally Sponsored",
    occupationTags: ["Laborer", "Unemployed"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 80,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "pradhan-mantri-awas-yojana-urban-pmay-u",
    title: "Pradhan Mantri Awas Yojana - Urban (PMAY-U)",
    description: "A housing initiative aimed at providing all-weather pucca houses to eligible urban beneficiaries, addressing urban housing shortages among EWS, LIG, and MIG categories.",
    category: "Housing & Urban Development",
    targetGroup: "Urban poor, slum dwellers, Economically Weaker Sections (EWS), Low Income Groups (LIG), and Middle Income Groups (MIG).",
    benefits: "Interest subsidies ranging from 3% to 6.5% on housing loans via the Credit Linked Subsidy Scheme (CLSS), or direct central assistance up to ₹1.5 Lakh for house construction.",
    eligibility: "Beneficiary family must not own a pucca house in their name anywhere in India. Income limits: EWS up to ₹3 Lakh, LIG up to ₹6 Lakh, MIG up to ₹18 Lakh annually.",
    applicationProcess: "Eligible individuals can register online through the PMAY-U official portal, or apply via local urban local bodies (ULBs) or designated CSCs.",
    requiredDocuments: ["Aadhaar Card", "Income Certificate", "Identity Proof", "Address Proof", "Affidavit of not owning a Pucca House", "Bank Passbook"],
    officialUrl: "https://pmay-urban.gov.in",
    startDate: "2015-06-25",
    endDate: "2026-12-31",
    ministry: "Ministry of Housing and Urban Affairs",
    schemeType: "Centrally Sponsored",
    occupationTags: ["All", "Salaried", "Self-Employed"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 70,
    incomeMin: "0",
    incomeMax: "1800000",
    isActive: true
  },
  {
    slug: "pradhan-mantri-svanidhi-pm-svanidhi",
    title: "Pradhan Mantri Street Vendor’s AtmaNirbhar Nidhi (PM SVANidhi)",
    description: "A special micro-credit facility scheme intended to provide affordable working capital loans to street vendors to resume their livelihoods post pandemic disruptions.",
    category: "Finance & Banking",
    targetGroup: "Street vendors, hawkers, and informal traders operating in urban, peri-urban, or rural environments.",
    benefits: "Initial working capital loan up to ₹10,000, eligible for an enhanced loan of ₹20,000 and ₹50,000 upon timely repayment. Includes a 7% interest subsidy and cashback on digital transactions.",
    eligibility: "Urban street vendors who were vending on or before March 24, 2020, and possess a Certificate of Vending or Letter of Recommendation from local municipal bodies.",
    applicationProcess: "Applications can be submitted via the PM SVANidhi portal, through a banking correspondent, or at local urban bodies and CSCs.",
    requiredDocuments: ["Aadhaar Card", "Voter Identity Card", "Certificate of Vending / Vendor ID card", "Bank Account Details"],
    officialUrl: "https://pmsvanidhi.mohua.gov.in",
    startDate: "2020-06-01",
    endDate: null,
    ministry: "Ministry of Housing and Urban Affairs",
    schemeType: "Central Sector",
    occupationTags: ["Street Vendor", "Trader", "Artisan"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 75,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "atal-pension-yojana-apy",
    title: "Atal Pension Yojana (APY)",
    description: "A pension scheme targeted focused on providing retirement financial security to workers in the unorganized sector, encouraging them to save voluntarily.",
    category: "Social Security & Pension",
    targetGroup: "Unorganized sector workers, laborers, domestic helps, and self-employed individuals.",
    benefits: "Guaranteed minimum monthly pension of ₹1,000, ₹2,000, ₹3,000, ₹4,000, or ₹5,000 after attaining 60 years of age, depending on the subscriber's contribution period and amount.",
    eligibility: "Any Indian citizen between 18 and 40 years of age who holds a savings bank account. Must not be an existing member of any statutory social security scheme or an income taxpayer.",
    applicationProcess: "Can be opened by approaching the bank or post office branch where the applicant holds a savings bank account, or through internet banking/mobile banking portals.",
    requiredDocuments: ["Aadhaar Card", "Savings Bank Account Number", "Mobile Number"],
    officialUrl: "https://www.npscra.nsdl.co.in",
    startDate: "2015-05-09",
    endDate: null,
    ministry: "Ministry of Finance",
    schemeType: "Central Sector",
    occupationTags: ["Laborer", "Self-Employed", "Domestic Worker", "Unemployed"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 40,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "pradhan-mantri-ujjwala-yojana-pmuy",
    title: "Pradhan Mantri Ujjwala Yojana (PMUY)",
    description: "A social welfare initiative providing clean cooking fuel (LPG connections) to women from below-poverty-line (BPL) households to replace health-hazardous conventional fuels.",
    category: "Utility & Energy",
    targetGroup: "Adult women belonging to economically disadvantaged households (BPL, SC/ST, most backward classes).",
    benefits: "Financial support of ₹1,600 for each PMUY LPG connection, covering the security deposit of cylinder, regulator, and installation costs, plus a free first LPG cylinder and stove refill.",
    eligibility: "Applicant must be an adult woman residing in an LPG-deprived household categorized under SECC 2011, Antyodaya Anna Yojana, or specified marginalized communities.",
    applicationProcess: "Apply online via the PMUY portal or submit a physical application form directly at local LPG distributorships.",
    requiredDocuments: ["Aadhaar Card of Applicant", "Ration Card issued by State Gov", "BPL Certificate / Income Certificate", "Bank Passbook"],
    officialUrl: "https://www.pmuy.gov.in",
    startDate: "2016-05-01",
    endDate: null,
    ministry: "Ministry of Petroleum and Natural Gas",
    schemeType: "Central Sector",
    occupationTags: ["Domestic Worker", "Unemployed"],
    stateTags: ["All"],
    genderTags: ["Female"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 100,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "pradhan-mantri-vishwakarma-scheme",
    title: "PM Vishwakarma Scheme",
    description: "A comprehensive scheme designed to provide end-to-end institutional support to traditional artisans and craftspeople who work with their hands and traditional tools.",
    category: "Skill Development & Employment",
    targetGroup: "Traditional artisans and craftsmen across 18 specified trades including carpenters, blacksmiths, potters, weavers, and tailors.",
    benefits: "Recognition via PM Vishwakarma Certificate and ID card, skill upgradation training with a daily stipend of ₹500, a toolkit incentive of ₹15,000, and collateral-free credit support up to ₹3 Lakh at a concessional interest rate of 5%.",
    eligibility: "An artisan practicing one of the 18 family-based traditional trades. Only one member per family is eligible. Excludes government servants and individuals who took similar business loans recently.",
    applicationProcess: "Registration must be completed online via the PM Vishwakarma portal through Common Service Centres (CSCs), followed by a three-step verification process.",
    requiredDocuments: ["Aadhaar Card", "Mobile Number linked with Aadhaar", "Bank Account Details", "Ration Card (for family mapping)"],
    officialUrl: "https://pmvishwakarma.gov.in",
    startDate: "2023-09-17",
    endDate: null,
    ministry: "Ministry of Micro, Small and Medium Enterprises",
    schemeType: "Central Sector",
    occupationTags: ["Artisan", "Self-Employed", "Technician", "Laborer"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 18,
    ageMax: 90,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "pm-shri-schools-pradhan-mantri-schools-for-rising-india",
    title: "PM SHRI Schools (PM Schools for Rising India)",
    description: "A centrally sponsored scheme aimed at upgrading and developing thousands of schools across the country to showcase all components of the National Education Policy (NEP) 2020.",
    category: "Education",
    targetGroup: "Students enrolled in selected state, central, and local body schools across primary, secondary, and senior secondary levels.",
    benefits: "Transformation of schools into smart, eco-friendly hubs with modern infrastructure, ICT smart classrooms, innovative pedagogy, career counseling, and advanced learning materials.",
    eligibility: "Schools apply through an online challenge portal; selections are made based on predefined infrastructure benchmarks and academic performance indicators.",
    applicationProcess: "Managed directly by state/central education boards and school administrators via the institutional PM SHRI challenge portal.",
    requiredDocuments: ["School UDISE Code", "School Infrastructure Assessment Report"],
    officialUrl: "https://pmshrischools.education.gov.in",
    startDate: "2022-09-07",
    endDate: "2027-03-31",
    ministry: "Ministry of Education",
    schemeType: "Centrally Sponsored",
    occupationTags: ["Student"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["Under 10th", "10th Pass", "12th Pass"],
    ageMin: 5,
    ageMax: 18,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  },
  {
    slug: "pradhan-mantri-jan-dhan-yojana-pmjdy",
    title: "Pradhan Mantri Jan Dhan Yojana (PMJDY)",
    description: "National Mission for Financial Inclusion to ensure access to financial services, namely, basic savings & deposit accounts, remittance, credit, insurance, and pension in an affordable manner.",
    category: "Finance & Banking",
    targetGroup: "Unbanked individuals, low-income households, and marginalized citizens.",
    benefits: "Basic savings bank account with no minimum balance requirement, free RuPay debit card, inbuilt ₹2,000,000 accidental insurance cover, and an overdraft facility up to ₹10,000 for eligible account holders.",
    eligibility: "Any Indian citizen who does not possess a bank account can open a basic savings account under this scheme.",
    applicationProcess: "Can be opened instantly at any commercial bank branch or through authorized Bank Mitras / Business Correspondents.",
    requiredDocuments: ["Aadhaar Card", "Voter ID Card / PAN Card", "Passport Size Photo", "NREGA Job Card"],
    officialUrl: "https://pmjdy.gov.in",
    startDate: "2014-08-28",
    endDate: null,
    ministry: "Ministry of Finance",
    schemeType: "Central Sector",
    occupationTags: ["All", "Unemployed", "Laborer"],
    stateTags: ["All"],
    genderTags: ["All"],
    educationTags: ["All"],
    ageMin: 10,
    ageMax: 100,
    incomeMin: null,
    incomeMax: null,
    isActive: true
  }
];